### ISSUE TITLE
Campaign scheduling function ignrores TimezoneID

### ISSUE THREAD

**Issue by wilburx9** [mailerlite/mailerlite-go#11] opened 2023-05-26 19:49 UTC
I suspect this is an issue with the web service (not this Go client) but I am raising this here with the hope that it gets escalated to the right team.

Take a look at [this function](https://github.com/wilburt/wilburx9.com/blob/16d9a837ac4d03bd4e5705180294552f15ced4e9/backend/broadcast.go#L97-L135).

According to the [API docs](https://developers.mailerlite.com/docs/campaigns.html#schedule-a-campaign), the `timezone_id` "Must be a valid timezone id, defaults to the account's timezone id". This means it will use the timezone id if it's passed, otherwise, it will use the account's timezone.

On the [dashboard](https://dashboard.mailerlite.com/account/profile), update your account time zone to any that is ahead of UTC; e.g. "Asia/Tokyo".

Now, if you call the campaign scheduling function as I did above, and pass 426 (UTC) to `TimezoneID` (assuming you execute the program on a machine with UTC time zone), the call with fail with:

> POST https://connect.mailerlite.com/api/campaigns/${CAMPAIGN_ID}/schedule: 422 Please select time in the future map[schedule.hours:[Please select time in the future]].

 

However, if you change the timezone on the dashboard to UTC, the API succeeds.

**Comment by jtarrio** [comment] 2023-05-26 22:31
That's because the field is actually `timezone`, not `timezone_id`. I raised this with the team previously and they've acknowledged it, so I expect the fix will be published soon. For now I'm using a forked version of mailerlite-go with the correct field name.

**Comment by wilburt** [comment] 2023-05-27 03:07
@jtarrio so you're saying both the docs and mailerlite-go are using the wrong field name?

**Comment by jtarrio** [comment] 2023-05-29 14:43
That's correct. I had the same issue with the timezone, where it seemed to be ignored, then I tried using `timezone` instead of `timezone_id` as the field, and that worked.

The API reference is not generated automatically from the API definitions, so they are not complete and they contain mistakes. For example, the docs don't tell you that, when you create a campaign, you _can_ specify the plain text version of the email using the `plain_text` field.

**Comment by robgordon89** [comment] 2023-09-13 09:36
I can confirm that this has been fixed in the upstream API.

Please use timezone_id now 👍

**Closed by robgordon89** 2023-09-13 09:36 UTC
